name = "codecrafters_http_server"
version = "4.0.1"


licences = ["Apache-2.0"]
description = "a misty Gleam web server"
repository = { type = "github", user = "Dannynsikak", repo = "HTTP-server" }
target = "erlang"
gleam = ">= 1.4.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.


[dependencies]
birl = "~> 1.3"
gleam_erlang = "~> 0.24"
gleam_http = "~> 3.5"
gleam_otp = "~> 0.9"
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
hpack_erl = "~> 0.3"
logging = "~> 1.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gramps = ">= 3.0.0 and < 4.0.0"
glisten = ">= 7.0.0 and < 8.0.0"
mist = ">= 4.0.1 and < 5.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
gleam_hackney = "~> 1.2"
